=== fermi-lat/Likelihood/xml/A1_Functions.dtd
<!ELEMENT function_library ((function)+ | (function_library)*) >
<!ATTLIST function_library 
          title CDATA #REQUIRED >
<!ELEMENT function (parameter*)>
<!ATTLIST function
          name       CDATA   #REQUIRED 
          type       CDATA   #REQUIRED >
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter 
          name       CDATA   #REQUIRED 
          value      CDATA   #REQUIRED 
	  unit       CDATA   #REQUIRED 
	  min        CDATA   #REQUIRED 
	  max        CDATA   #REQUIRED 
	  free       CDATA   #REQUIRED 
	  scale      CDATA   #REQUIRED >

=== fermi-lat/Likelihood/xml/A1_Functions.xml
<?xml version='1.0' standalone='no'?>
<!DOCTYPE function_library SYSTEM "A1_Functions.dtd" >
<function_library title="prototype Functions">
   <function name="Bright Source Power-law" type="PowerLaw">
   <!-- This prototype provides *very roughly* appropriate values for 
        bright EGRET point sources. -->
      <parameter name="Prefactor" 
                 value="10"
                 unit="cm^-2s^-1MeV^-1"
                 min ="1e-3"
                 max="1e3"
                 free="true"
                 scale="1e-9"/>
      <parameter name="Index"
                 value="-2"
                 unit="none"
                 min="-3.5"
                 max="-1"
                 free="true"
                 scale="1"/>
      <parameter name="Scale"
                 value="100"
                 unit="none"
                 min="50"
                 max="200"
                 free="false"
                 scale="1"/>
   </function>
   <function name="Galactic Diffuse Power-law" type="PowerLaw">
   <!-- Use this prototype with the EGRET Galactic diffuse model map for
        E > 100 MeV. -->
      <parameter name="Prefactor"
                 value="6.31"
                 unit="cm^-2s^-1MeV^-1"
                 min ="1e-3"
                 max="1e3"
                 free="true"
                 scale="1e-3"/>
      <parameter name="Index"
                 value="-2.1"
                 unit="none"
                 min="-3.5"
                 max="-1"
                 free="true"
                 scale="1"/>
      <parameter name="Scale"
                 value="100"
                 unit="none"
                 min="50"
                 max="200"
                 free="false"
                 scale="1"/>
   </function>
   <function name="Extragalactic Diffuse Power-law" type="PowerLaw">
   <!-- Power-law spectrum appropriate for the isotropic extragalactic
        diffuse as measured by Sreekumar et al. 1998 -->
      <parameter name="Prefactor"
                 value="1.32"
                 unit="cm^-2s^-1MeV^-1"
                 min ="1e-5"
                 max="1e2"
                 free="true"
                 scale="1e-7"/>
      <parameter name="Index"
                 value="-2.1"
                 unit="none"
                 min="-3.5"
                 max="-1"
                 free="true"
                 scale="1"/>
      <parameter name="Scale"
                 value="100"
                 unit="none"
                 min="50"
                 max="200"
                 free="false"
                 scale="1"/>
   </function>
</function_library>
