=== fermi-lat/Likelihood/xml/A1_Sources.dtd
<!ELEMENT source_library ((source)+ | (source_library)*) >
<!ATTLIST source_library 
          title CDATA #REQUIRED 
          function_library CDATA " " >
<!ELEMENT source (spectrum, spatialModel) >
<!ATTLIST source
          name       CDATA   #REQUIRED 
          type       CDATA   #REQUIRED >
<!ELEMENT spectrum (parameter*) >
<!ATTLIST spectrum 
          type       CDATA   #REQUIRED 
          file       CDATA   " " >
<!ELEMENT spatialModel (parameter*) >
<!ATTLIST spatialModel
          type       CDATA   #REQUIRED 
          file       CDATA   " " >
<!ELEMENT parameter EMPTY >
<!ATTLIST parameter 
          name       CDATA   #REQUIRED 
          value      CDATA   #REQUIRED 
	  unit       CDATA   " "
	  min        CDATA   #REQUIRED 
	  max        CDATA   #REQUIRED 
	  free       CDATA   #REQUIRED 
	  scale      CDATA   #REQUIRED >

=== fermi-lat/Likelihood/xml/A1_Sources.xml
<?xml version='1.0' standalone='no'?>
<!DOCTYPE source_library SYSTEM "A1_Sources.dtd" >
<source_library title="prototype sources" 
                function_library="$(LIKELIHOODXMLPATH)/A1_Functions.xml">
   <source name="Bright Point Source" type="PointSource">
      <spectrum type="Bright Source Power-law"></spectrum>
      <spatialModel type="SkyDirFunction">
         <parameter name="RA"
                    value="0"
                    min="-180"
                    max="180"
                    free="false"
                    scale="1"/>
         <parameter name="DEC"
                    value="0"
                    min="-90"
                    max="90"
                    free="false"
                    scale="1"/>
      </spatialModel>
   </source>

   <source name="Galactic Diffuse Emission" type="DiffuseSource">
      <spectrum type="Galactic Diffuse Power-law"></spectrum>
      <spatialModel type="SpatialMap" 
                    file="$(EXTFILESSYS)/galdiffuse/EGRET_diffuse_cel.fits">
      </spatialModel>
   </source>

   <source name="Extragalactic Diffuse Emission" type="DiffuseSource">
      <spectrum type="Extragalactic Diffuse Power-law"></spectrum>
      <spatialModel type="ConstantValue">
         <parameter name="Value"
                    value="1"
                    min="0"
                    max="10"
                    free="false"
                    scale="1"/>
      </spatialModel>
   </source>
</source_library>

=== fermi-lat/Likelihood/data/Crab_model.xml
<?xml version="1.0" ?>
<!DOCTYPE source_library
  SYSTEM '$(LIKELIHOODROOT)/xml/A1_Sources.dtd'>
<source_library title="source library">
    <source name="Crab Pulsar" type="PointSource">
      <spectrum type="PowerLaw">
        <parameter free="1" max="1000.0" min="0.001" name="Prefactor" scale="1e-09" value="27.0"/>
        <parameter free="1" max="-1.0" min="-3.5" name="Index" scale="1.0" value="-2.19"/>
        <parameter free="0" max="2000.0" min="30.0" name="Scale" scale="1.0" value="100.0"/>
      </spectrum>
      <spatialModel type="SkyDirFunction">
        <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1.0" value="83.57"/>
        <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1.0" value="22.01"/>
      </spatialModel>
    </source>
  </source_library>

=== fermi-lat/Likelihood/data/anticenter_model_3.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE source_library SYSTEM "$(LIKELIHOODXMLPATH)/A1_Sources.dtd" >
<source_library title="source library">
<source name="Crab Pulsar" type="PointSource">
    <spectrum type="PowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="1e-09" value="27"/>
      <parameter free="1" max="-1" min="-3.5" name="Index" scale="1" value="-2.19"/>
      <parameter free="0" max="2000" min="30" name="Scale" scale="1" value="100"/>
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1" value="83.57"/>
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1" value="22.01"/>
    </spatialModel>
  </source>
<source name="Geminga" type="PointSource">
    <spectrum type="PowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="1e-09" value="23.29"/>
      <parameter free="1" max="-1" min="-3.5" name="Index" scale="1" value="-1.66"/>
      <parameter free="0" max="2000" min="30" name="Scale" scale="1" value="100"/>
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1" value="98.49"/>
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1" value="17.86"/>
    </spatialModel>
  </source>
</source_library>

=== fermi-lat/Likelihood/xml/A1_Srcs_noFuncLib.xml
<?xml version='1.0' standalone='no'?>
<!DOCTYPE source_library SYSTEM "A1_Sources.dtd" >
<source_library title="prototype sources" >
   <source name="Bright Point Source" type="PointSource">
      <spectrum type="PowerLaw"></spectrum>
      <spatialModel type="SkyDirFunction">
         <parameter name="RA"
                    value="0"
                    unit="degrees"
                    min="-180"
                    max="180"
                    free="false"
                    scale="1"/>
         <parameter name="DEC"
                    value="0"
                    unit="degrees"
                    min="-90"
                    max="90"
                    free="false"
                    scale="1"/>
      </spatialModel>
   </source>

   <source name="Galactic Diffuse Emission" type="DiffuseSource">
      <spectrum type="PowerLaw"></spectrum>
      <spatialModel type="SpatialMap" 
                    file="$(EXTFILESSYS)/galdiffuse/EGRET_diffuse_cel.fits">
      </spatialModel>
   </source>

   <source name="Extragalactic Diffuse Emission" type="DiffuseSource">
      <spectrum type="PowerLaw"></spectrum>
      <spatialModel type="ConstantValue">
         <parameter name="Value"
                    value="1"
                    unit="none"
                    min="0"
                    max="10"
                    free="false"
                    scale="1"/>
      </spatialModel>
   </source>
</source_library>

=== fermi-lat/Likelihood/data/anticenter_model_bpl.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE source_library SYSTEM "$(LIKELIHOODXMLPATH)/A1_Sources.dtd" >
<source_library title="source library">
<source name="Extragalactic Diffuse" type="DiffuseSource">
    <spectrum type="PowerLaw">
      <parameter free="1" max="100" min="1e-05" name="Prefactor" scale="1e-07" value="1.32"/>
      <parameter free="0" max="-1" min="-3.5" name="Index" scale="1" value="-2.1"/>
      <parameter free="0" max="200" min="50" name="Scale" scale="1" value="100"/>
    </spectrum>
    <spatialModel type="ConstantValue">
       <parameter free="0" max="10" min="0" name="Value" scale="1" value="1"/>
    </spatialModel>
  </source>
<source name="Galactic Diffuse" type="DiffuseSource">
    <spectrum type="PowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="0.001" value="11"/>
      <parameter free="0" max="-1" min="-3.5" name="Index" scale="1" value="-2.1"/>
      <parameter free="0" max="200" min="50" name="Scale" scale="1" value="100"/>
    </spectrum>
    <spatialModel file="$(EXTFILESSYS)/galdiffuse/EGRET_diffuse_cel.fits" type="SpatialMap">
      <parameter free="0" max="1000" min="0.001" name="Prefactor" scale="1" value="1"/>
    </spatialModel>
  </source>
<source name="PKS 0528+134" type="PointSource">
    <spectrum type="PowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="1e-09" value="13.65"/>
      <parameter free="1" max="-1" min="-3.5" name="Index" scale="1" value="-2.46"/>
      <parameter free="0" max="2000" min="30" name="Scale" scale="1" value="100"/>
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1" value="82.74"/>
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1" value="13.38"/>
    </spatialModel>
  </source>
<source name="Crab Pulsar" type="PointSource">
    <spectrum type="BrokenPowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="1e-09" value="27"/>
      <parameter free="1" max="-1" min="-5." name="Index1" scale="1" value="-2.19"/>
      <parameter free="1" max="-1" min="-6." name="Index2" scale="1" value="-4.89"/>
      <parameter free="0" max="10000" min="30" name="BreakValue" scale="1" value="1500"/>
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1" value="83.57"/>
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1" value="22.01"/>
    </spatialModel>
  </source>
<source name="Geminga" type="PointSource">
    <spectrum type="BrokenPowerLaw">
      <parameter free="1" max="1000" min="0.001" name="Prefactor" scale="1e-09" value="23.29"/>
      <parameter free="1" max="-1" min="-5" name="Index1" scale="1" value="-1.66"/>
      <parameter free="1" max="-1" min="-5" name="Index2" scale="1" value="-3.1"/>
      <parameter free="0" max="10000" min="30" name="BreakValue" scale="1" value="2000"/>
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="RA" scale="1" value="98.49"/>
      <parameter free="0" max="3.40282e+38" min="-3.40282e+38" name="DEC" scale="1" value="17.86"/>
    </spatialModel>
  </source>
</source_library>
